package com.StudentManagmentSystem.SMS.model;

public enum Permissions {
    CREATE_COURSE,
    GET_ALL_COURSES,
    UPDATE_COURSE,
    GET_COURSE,
    DELETE_COURSE,

    
    CREATE_COURSE_OFFERING,
    GET_ALL_COURSES_OFFERING,
    GET_COURSES_OFFERING,

    CREATE_ENROLLMENT,
    GET_ALL_ENROLLMENT,
    GET_ENROLLMENT,
    UPDATE_ENROLLMENT,
    DELETE_ENROLLMENT,

    ADD_MARKS,
    GET_ALL_MARKS,
    GET_MARKS,
    UPDATE_MARKS,
    DELETE_MARKS,

    CREATE_SECTION,
    GET_ALL_SECTIONS,
    GET_SECTION,
    UPDATE_SECTION,
    DELETE_SECTION,

    CREATE_SEMESTER,
    GET_ALL_SEMESTER,
    GET_SEMESTER,
    UPDATE_SEMESTER,
    DELETE_SEMESTER,

    CREATE_STUDENT,
    DELETE_STUDENT,
    UPDATE_STUDENT,
    GET_All_STUDENT,
    GET_STUDENT,

    CREATE_TEACHER,
    DELETE_TEACHER,
    UPDATE_TEACHER,
    GET_ALL_TEACHER,
    GET_TEACHER
}
