spring.application.name=SMS

# PROFILE MANAGEMENT
# Defaults to "local" profile when run on your PC.
# When run on Render, Render injects SPRING_PROFILES_ACTIVE=prod to switch it.
# spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# DATABASE CONFIGURATION
# If the active profile is "prod", it reads from these variables.
# If the active profile is "local", Spring overrides these with your gitignored file.
spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=${PORT:8080}

jwt.secretkey=${JWT_SECRETKEY}
