spring.application.name=SMS

# Database Configuration (Reads Render variables, or ignores if running locally)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# Port and Profile Management
server.port=${PORT:8080}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# JWT Key Reads Render's JWT_SECRETKEY environment variable
jwt.secretkey=${JWT_SECRETKEY}
